version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - REDIS_URL=redis://redis:6379
    depends_on:
      - kafka
      - redis

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 